/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FaAccordion {
    'text': any;
  }
}

declare global {


  interface HTMLFaAccordionElement extends Components.FaAccordion, HTMLStencilElement {}
  var HTMLFaAccordionElement: {
    prototype: HTMLFaAccordionElement;
    new (): HTMLFaAccordionElement;
  };
  interface HTMLElementTagNameMap {
    'fa-accordion': HTMLFaAccordionElement;
  }
}

declare namespace LocalJSX {
  interface FaAccordion extends JSXBase.HTMLAttributes<HTMLFaAccordionElement> {
    'text'?: any;
  }

  interface IntrinsicElements {
    'fa-accordion': FaAccordion;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


